
const listTranslationsId = ["ASV", "KJV", "NRT", "RST"];

const listTranslationsName = [
  "American Standard Version",
  "King James Version",
  "Новый русский перевод",
  "Синодальный перевод"
];


const listBooksOldTestamentRu = [
  "Бытие",
  "Исход",
  "Левит",
  "Числа",
  "Второзаконие",
  "Книга Иисуса Навина",
  "Книга Судей",
  "Книга Руфь",
  "1-ая Царств",
  "2-ая Царств",
  "3-яя Царств",
  "4-ая Царств",
  "1-ая Паралипоменон",
  "2-ая Паралипоменон",
  "Книга Ездры",
  "Книга Неемии",
  "Книга Есфирь",
  "Книга Иова",
  "Псалтирь",
  "Книга Притчей",
  "Книга Екклесиаста",
  "Книга Песни Песний",
  "Книга Исаии",
  "Книга Иеремии",
  "Плач Иеремии",
  "Книга Иезекииля",
  "Книга Даниила",
  "Книга Осии",
  "Книга Иоиля",
  "Книга Амоса",
  "Книга Авдия",
  "Книга Ионы",
  "Книга Михея",
  "Книга Наума",
  "Книга Аввакума",
  "Книга Софонии",
  "Книга Аггея",
  "Книга Захарии",
  "Книга Малахии"
];

const listBooksNewTestamentRu = [
  "Евангелие от Матфея",
  "Евангелие от Марка",
  "Евангелие от Луки",
  "Евангелие от Иоанна",
  "Деяния Апостолов",
  "Послание к Римлянам ",
  "1-ое к Коринфянам ",
  "2-ое к Коринфянам ",
  "Послание к Галатам",
  "Послание к Ефесянам",
  "Послание к Филиппийцам ",
  "Послание к Колоссянам ",
  "1-ое к Фессалоникийцам ",
  "2-ое к Фессалоникийцам ",
  "1-ое Тимофею",
  "2-ое Тимофею",
  "Послание к Титу",
  "Послание к Филимону",
  "Послание к Евреям",
  "Послание Иакова",
  "1-ое Петра",
  "2-ое Петра",
  "1-ое Иоанна",
  "2-ое Иоанна",
  "3-ее Иоанна",
  "Послание Иуды ",
  "Откровение"
];

const listBooksOldTestamentEn = [
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1 Samuel",
  "2 Samuel",
  "1 Kings",
  "2 Kings",
  "1 Chronicles",
  "2 Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "Song of Solomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi"
];


const listBooksNewTestamentEn = [
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts of the Apostles",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "2 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1 Peter",
  "2 Peter",
  "1 John",
  "2 John",
  "3 John",
  "Jude",
  "Revelation"
];