const mapCountChapters = {
  "Genesis": 50,
  "Exodus": 40,
  "Leviticus": 27,
  "Numbers": 36,
  "Deuteronomy": 34,
  "Joshua": 24,
  "Judges": 21,
  "Ruth": 4,
  "1 Samuel": 31,
  "2 Samuel": 24,
  "1 Kings": 22,
  "2 Kings": 25,
  "1 Chronicles": 29,
  "2 Chronicles": 36,
  "Ezra": 10,
  "Nehemiah": 13,
  "Esther": 10,
  "Job": 42,
  "Psalms": 150,
  "Proverbs": 31,
  "Ecclesiastes": 12,
  "Song of Solomon": 8,
  "Isaiah": 66,
  "Jeremiah": 52,
  "Lamentations": 5,
  "Ezekiel": 48,
  "Daniel": 12,
  "Hosea": 14,
  "Joel": 3,
  "Amos": 9,
  "Obadiah": 1,
  "Jonah": 4,
  "Micah": 7,
  "Nahum": 3,
  "Habakkuk": 3,
  "Zephaniah": 3,
  "Haggai": 2,
  "Zechariah": 14,
  "Malachi": 4,
  "Matthew": 28,
  "Mark": 16,
  "Luke": 24,
  "John": 21,
  "Acts of the Apostles": 28,
  "Romans": 16,
  "1 Corinthians": 16,
  "2 Corinthians": 13,
  "Galatians": 6,
  "Ephesians": 6,
  "Philippians": 4,
  "Colossians": 4,
  "1 Thessalonians": 5,
  "2 Thessalonians": 3,
  "1 Timothy": 6,
  "2 Timothy": 4,
  "Titus": 3,
  "Philemon": 1,
  "Hebrews": 13,
  "James": 5,
  "1 Peter": 5,
  "2 Peter": 3,
  "1 John": 5,
  "2 John": 1,
  "3 John": 1,
  "Jude": 1,
  "Revelation": 22
};

const mapImages = {
  "Genesis": "assets/images/genesis.jpg",
  "Exodus": "assets/images/exodus.jpg",
  "Leviticus": "",
  "Numbers": "",
  "Deuteronomy": "",
  "Joshua": "",
  "Judges": "",
  "Ruth": "",
  "1 Samuel": "",
  "2 Samuel": "",
  "1 Kings": "",
  "2 Kings": "",
  "1 Chronicles": "",
  "2 Chronicles": "",
  "Ezra": "",
  "Nehemiah": "",
  "Esther": "",
  "Job": "",
  "Psalms": "",
  "Proverbs": "",
  "Ecclesiastes": "",
  "Song of Solomon": "",
  "Isaiah": "",
  "Jeremiah": "",
  "Lamentations": "",
  "Ezekiel": "",
  "Daniel": "",
  "Hosea": "",
  "Joel": "",
  "Amos": "",
  "Obadiah": "",
  "Jonah": "",
  "Micah": "",
  "Nahum": "",
  "Habakkuk": "",
  "Zephaniah": "",
  "Haggai": "",
  "Zechariah": "",
  "Malachi": "",
  "Matthew": "",
  "Mark": "",
  "Luke": "",
  "John": "",
  "Acts of the Apostles": "",
  "Romans": "",
  "1 Corinthians": "",
  "2 Corinthians": "",
  "Galatians": "",
  "Ephesians": "",
  "Philippians": "",
  "Colossians": "",
  "1 Thessalonians": "",
  "2 Thessalonians": "",
  "1 Timothy": "",
  "2 Timothy": "",
  "Titus": "",
  "Philemon": "",
  "Hebrews": "",
  "James": "",
  "1 Peter": "",
  "2 Peter": "",
  "1 John": "",
  "2 John": "",
  "3 John": "",
  "Jude": "",
  "Revelation": ""
};

const mapBooksRu = {
  "Genesis": "Бытие",
  "Exodus": "Исход",
  "Leviticus": "Левит",
  "Numbers": "Числа",
  "Deuteronomy": "Второзаконие",
  "Joshua": "Книга Иисуса Навина",
  "Judges": "Книга Судей",
  "Ruth": "Книга Руфь",
  "1 Samuel": "1-ая Царств",
  "2 Samuel": "2-ая Царств",
  "1 Kings": "3-ая Царств",
  "2 Kings": "4-ая Царств",
  "1 Chronicles": "1-ая Паралипоменон",
  "2 Chronicles": "2-ая Паралипоменон",
  "Ezra": "Книга Ездры",
  "Nehemiah": "Книга Неемии",
  "Esther": "Книга Есфирь",
  "Job": "Книга Иова",
  "Psalms": "Псалтирь",
  "Proverbs": "Книга Притчей",
  "Ecclesiastes": "Книга Екклесиаста",
  "Song of Solomon": "Книга Песни Песний",
  "Isaiah": "Книга Исаии",
  "Jeremiah": "Книга Иеремии",
  "Lamentations": "Плач Иеремии",
  "Ezekiel": "Книга Иезекииля",
  "Daniel": "Книга Даниила",
  "Hosea": "Книга Осии",
  "Joel": "Книга Иоиля",
  "Amos": "Книга Амоса",
  "Obadiah": "Книга Авдия",
  "Jonah": "Книга Ионы",
  "Micah": "Книга Михея",
  "Nahum": "Книга Наума",
  "Habakkuk": "Книга Аввакума",
  "Zephaniah": "Книга Софонии",
  "Haggai": "Книга Аггея",
  "Zechariah": "Книга Захарии",
  "Malachi": "Книга Малахии",
  "Matthew": "Евангелие от Матфея",
  "Mark": "Евангелие от Марка",
  "Luke": "Евангелие от Луки",
  "John": "Евангелие от Иоанна",
  "Acts of the Apostles": "Деяния Апостолов",
  "Romans": "Послание к Римлянам",
  "1 Corinthians": "1-ое к Коринфянам",
  "2 Corinthians": "2-ое к Коринфянам",
  "Galatians": "Послание к Галатам",
  "Ephesians": "Послание к Ефесянам",
  "Philippians": "Послание к Филиппийцам",
  "Colossians": "Послание к Колоссянам",
  "1 Thessalonians": "1-ое к Фессалоникийцам",
  "2 Thessalonians": "2-ое к Фессалоникийцам",
  "1 Timothy": "1-ое Тимофею",
  "2 Timothy": "2-ое Тимофею",
  "Titus": "Послание к Титу",
  "Philemon": "Послание к Филимону",
  "Hebrews": "Послание к Евреям",
  "James": "Послание Иакова",
  "1 Peter": "1-ое Петра",
  "2 Peter": "2-ое Петра",
  "1 John": "1-ое Иоанна",
  "2 John": "2-ое Иоанна",
  "3 John": "3-ое Иоанна",
  "Jude": "Послание Иуды",
  "Revelation": "Откровение"
};

const mapMonthsRu = {
  1: "Января",
  2: "Февраля",
  3: "Марта",
  4: "Апреля",
  5: "Мая",
  6: "Июня",
  7: "Июля",
  8: "Августа",
  9: "Сентября",
  10: "Октября",
  11: "Ноября",
  12: "Декабря"
};

const mapMonthsEn = {
  1: "January",
  2: "February",
  3: "March",
  4: "April",
  5: "May",
  6: "June",
  7: "July",
  8: "August",
  9: "September",
  10: "October",
  11: "November",
  12: "December"
};